IBC_2021_OCCUPANT_LOADS = [
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "accessory_storage_gross", "name": "Accessory storage areas, mechanical equipment room, gross", "factor": 300, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "agricultural_gross", "name": "Agricultural building, gross", "factor": 300, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "aircraft_hangar_gross", "name": "Aircraft hangars, gross", "factor": 500, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "airport_terminal_baggage_gross", "name": "Airport terminal baggage claim, gross", "factor": 20, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "airport_terminal_ticketing_gross", "name": "Airport terminal ticket counters, waiting areas, concourses, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_concentrated_net", "name": "Assembly without fixed seats, concentrated (chairs only-not fixed), net", "factor": 7, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_standing_net", "name": "Assembly without fixed seats, standing space, net", "factor": 5, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_unconcentrated_net", "name": "Assembly without fixed seats, unconcentrated (tables and chairs), net", "factor": 15, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_exhibit_gallery_net", "name": "Assembly with fixed seats, exhibit gallery and museum, net", "factor": 30, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_gaming_floor_net", "name": "Casino gaming floors, net", "factor": 11, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_skating_rink_net", "name": "Skating rinks, swimming pools, net", "factor": 50, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_stage_net", "name": "Stages and platforms, net", "factor": 15, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "assembly_waiting_areas_gross", "name": "Waiting areas, gross", "factor": 15, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "business_gross", "name": "Business areas, gross", "factor": 150, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "courtroom_other_gross", "name": "Courtrooms - other areas, gross", "factor": 40, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "courtroom_seating_fixed", "name": "Courtrooms - seating areas, fixed seating", "factor": 1, "area_type": "fixed seating"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "day_care_gross", "name": "Day care, gross", "factor": 35, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "dormitory_gross", "name": "Dormitories, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "educational_classroom_net", "name": "Educational classrooms area, net", "factor": 20, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "exercise_gross", "name": "Exercise rooms, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "factory_industrial_gross", "name": "Factory and industrial areas, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "industrial_gross", "name": "Industrial areas, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "institutional_inpatient_treatment_gross", "name": "Institutional areas, inpatient treatment areas, gross", "factor": 240, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "institutional_outpatient_gross", "name": "Institutional areas, outpatient areas, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "kitchen_commercial_gross", "name": "Kitchens, commercial, gross", "factor": 200, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "library_reading_rooms_net", "name": "Library reading rooms, net", "factor": 50, "area_type": "net"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "library_stack_gross", "name": "Library stack area, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "locker_room_gross", "name": "Locker rooms, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "mall_building_covered_gross", "name": "Mall buildings, covered and open, gross", "factor": 30, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "mercantile_sales_gross", "name": "Mercantile sales areas, gross", "factor": 60, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "mercantile_stockroom_gross", "name": "Mercantile stockrooms, gross", "factor": 300, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "residential_gross", "name": "Residential, gross", "factor": 200, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "residential_boarding_gross", "name": "Residential boarding houses, gross", "factor": 200, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "skateboard_tennis_gross", "name": "Skateboard parks, tennis courts and similar outdoor activity areas, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "storage_warehouse_gross", "name": "Storage, warehouse, gross", "factor": 500, "area_type": "gross"},
    {"code_ref": "IBC 2021 Table 1004.5", "function_key": "waiting_areas_gross", "name": "Waiting areas, transportation terminals, gross", "factor": 15, "area_type": "gross"},
]

NFPA_101_OCCUPANT_LOADS = [
    # --- Assembly Use ---
    {"code_ref": "NFPA 101", "function_key": "assembly_concentrated_net", "name": "Assembly, concentrated use without fixed seating, net", "factor": 7, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "assembly_unconcentrated_net", "name": "Assembly, less concentrated use without fixed seating, net", "factor": 15, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "assembly_kitchens_gross", "name": "Assembly, kitchens, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_library_stack_gross", "name": "Assembly, library stack areas, gross", "factor": 100, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_library_reading_net", "name": "Assembly, library reading rooms, net", "factor": 50, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "assembly_swimming_pools_gross", "name": "Assembly, swimming pools (water surface), gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_pool_decks_gross", "name": "Assembly, swimming pool decks, gross", "factor": 30, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_exercise_equipment_gross", "name": "Assembly, exercise rooms with equipment, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_exercise_no_equipment_gross", "name": "Assembly, exercise rooms without equipment, gross", "factor": 15, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_stages_net", "name": "Assembly, stages, net", "factor": 15, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "assembly_catwalks_net", "name": "Assembly, lighting and access catwalks, galleries, gridirons, net", "factor": 100, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "assembly_casinos_gross", "name": "Assembly, casinos and similar gaming areas, gross", "factor": 11, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "assembly_skating_rinks_gross", "name": "Assembly, skating rinks, gross", "factor": 50, "area_type": "gross"},
    # --- Business Use ---
    {"code_ref": "NFPA 101", "function_key": "business_gross", "name": "Business use, gross", "factor": 150, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "business_concentrated_gross", "name": "Business, concentrated use, gross", "factor": 50, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "business_atc_tower_gross", "name": "Business, airport traffic control tower observation levels, gross", "factor": 40, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "business_collab_small_gross", "name": "Business, collaboration rooms/spaces 450 sf or less, gross", "factor": 30, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "business_collab_large_gross", "name": "Business, collaboration rooms/spaces over 450 sf, gross", "factor": 15, "area_type": "gross"},
    # --- Day-Care Use ---
    {"code_ref": "NFPA 101", "function_key": "day_care_net", "name": "Day-care use, net", "factor": 35, "area_type": "net"},
    # --- Detention and Correctional Use ---
    {"code_ref": "NFPA 101", "function_key": "detention_gross", "name": "Detention and correctional use, gross", "factor": 120, "area_type": "gross"},
    # --- Educational Use ---
    {"code_ref": "NFPA 101", "function_key": "educational_classroom_net", "name": "Educational, classrooms, net", "factor": 20, "area_type": "net"},
    {"code_ref": "NFPA 101", "function_key": "educational_shops_labs_net", "name": "Educational, shops, laboratories, vocational rooms, net", "factor": 50, "area_type": "net"},
    # --- Health Care Use ---
    {"code_ref": "NFPA 101", "function_key": "healthcare_inpatient_gross", "name": "Health care, inpatient treatment departments, gross", "factor": 240, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "healthcare_sleeping_gross", "name": "Health care, sleeping departments, gross", "factor": 120, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "healthcare_ambulatory_gross", "name": "Health care, ambulatory health care, gross", "factor": 150, "area_type": "gross"},
    # --- Industrial Use ---
    {"code_ref": "NFPA 101", "function_key": "industrial_gross", "name": "Industrial, general and high-hazard, gross", "factor": 100, "area_type": "gross"},
    # --- Mercantile Use ---
    {"code_ref": "NFPA 101", "function_key": "mercantile_street_floor_gross", "name": "Mercantile, sales area on street floor, gross", "factor": 30, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "mercantile_two_street_floors_gross", "name": "Mercantile, sales area on two or more street floors, gross", "factor": 40, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "mercantile_below_street_gross", "name": "Mercantile, sales area on floor below street floor, gross", "factor": 30, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "mercantile_above_street_gross", "name": "Mercantile, sales area on floors above street floor, gross", "factor": 60, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "mercantile_storage_gross", "name": "Mercantile, storage, receiving, and shipping (not open to public), gross", "factor": 300, "area_type": "gross"},
    # --- Residential Use ---
    {"code_ref": "NFPA 101", "function_key": "residential_hotels_gross", "name": "Residential, hotels and dormitories, gross", "factor": 200, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "residential_apartments_gross", "name": "Residential, apartment buildings, gross", "factor": 200, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "residential_board_care_gross", "name": "Residential, board and care (large), gross", "factor": 200, "area_type": "gross"},
    # --- Storage Use ---
    {"code_ref": "NFPA 101", "function_key": "storage_mercantile_gross", "name": "Storage, in mercantile occupancies, gross", "factor": 300, "area_type": "gross"},
    {"code_ref": "NFPA 101", "function_key": "storage_other_gross", "name": "Storage, in other than storage and mercantile occupancies, gross", "factor": 500, "area_type": "gross"},
]

OCCUPANT_LOAD_STANDARDS = {
    "IBC 2021": IBC_2021_OCCUPANT_LOADS,
    "NFPA 101": NFPA_101_OCCUPANT_LOADS,
}

PLUMBING_FIXTURE_CATEGORIES = [
    # --- 1  Assembly ---
    {
        "key": "assembly_theaters",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Theaters and other buildings for the performing arts and motion pictures",
        "label": "1 - Assembly: Theaters and performing arts",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 125,
        "wc_female": 65,
        "lav_male": 200,
        "lav_female": 200,
        "bath": None,
        "drinking": 500,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_nightclubs",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Nightclubs, bars, taverns, dance halls and buildings for similar purposes",
        "label": "1 - Assembly: Nightclubs, bars, taverns",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 40,
        "wc_female": 40,
        "lav_male": 75,
        "lav_female": 75,
        "bath": None,
        "drinking": 500,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_restaurants",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Restaurants, banquet halls and food courts",
        "label": "1 - Assembly: Restaurants, banquet halls",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 75,
        "wc_female": 75,
        "lav_male": 200,
        "lav_female": 200,
        "bath": None,
        "drinking": 500,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_casino_gaming",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Casino gaming areas",
        "label": "1 - Assembly: Casino gaming areas",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": {"per": 100, "first": 400, "then_per": 250},
        "wc_female": {"per": 50, "first": 400, "then_per": 150},
        "lav_male": {"per": 250, "first": 750, "then_per": 500},
        "lav_female": {"per": 250, "first": 750, "then_per": 500},
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_auditoriums",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Auditoriums without permanent seating, art galleries, exhibition halls, museums, lecture halls, libraries, arcades and gymnasiums",
        "label": "1 - Assembly: Auditoriums, galleries, museums",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 125,
        "wc_female": 65,
        "lav_male": 200,
        "lav_female": 200,
        "bath": None,
        "drinking": 500,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_passenger_terminals",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Passenger terminals and transportation facilities",
        "label": "1 - Assembly: Passenger terminals",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 500,
        "wc_female": 500,
        "lav_male": 750,
        "lav_female": 750,
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_worship",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Places of worship and other religious services",
        "label": "1 - Assembly: Places of worship",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 150,
        "wc_female": 75,
        "lav_male": 200,
        "lav_female": 200,
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_coliseums_indoor",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Coliseums, arenas, skating rinks, pools and tennis courts for indoor sporting events and activities",
        "label": "1 - Assembly: Coliseums, arenas (indoor)",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": {"per": 75, "first": 1500, "then_per": 120},
        "wc_female": {"per": 40, "first": 1520, "then_per": 60},
        "lav_male": 200,
        "lav_female": 150,
        "bath": 150,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "assembly_stadiums_outdoor",
        "classification_no": 1,
        "classification": "Assembly",
        "description": "Stadiums, amusement parks, bleachers and grandstands for outdoor sporting events and activities",
        "label": "1 - Assembly: Stadiums, outdoor sports",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": {"per": 75, "first": 1500, "then_per": 120},
        "wc_female": {"per": 40, "first": 1520, "then_per": 60},
        "lav_male": 200,
        "lav_female": 150,
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    # --- 2  Business ---
    {
        "key": "business",
        "classification_no": 2,
        "classification": "Business",
        "description": "Buildings for the transaction of business, professional services, other services involving merchandise, office buildings, banks, light industrial, ambulatory care and similar uses",
        "label": "2 - Business",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": {"per": 25, "first": 50, "then_per": 50},
        "wc_female": {"per": 25, "first": 50, "then_per": 50},
        "lav_male": {"per": 40, "first": 80, "then_per": 80},
        "lav_female": {"per": 40, "first": 80, "then_per": 80},
        "bath": None,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "business",
    },
    # --- 3  Educational ---
    {
        "key": "educational",
        "classification_no": 3,
        "classification": "Educational",
        "description": "Educational facilities",
        "label": "3 - Educational",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 50,
        "wc_female": 50,
        "lav_male": 50,
        "lav_female": 50,
        "bath": None,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    # --- 4  Factory and industrial ---
    {
        "key": "factory_industrial",
        "classification_no": 4,
        "classification": "Factory and industrial",
        "description": "Structures in which occupants are engaged in work fabricating, assembly or processing of products or materials",
        "label": "4 - Factory and industrial",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 100,
        "wc_female": 100,
        "lav_male": 100,
        "lav_female": 100,
        "bath": None,
        "drinking": 400,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    # --- 5  Institutional ---
    {
        "key": "institutional_custodial",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Custodial care facilities",
        "label": "5 - Institutional: Custodial care",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 10,
        "wc_female": 10,
        "lav_male": 10,
        "lav_female": 10,
        "bath": 8,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "institutional_employees_hospitals",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Employees in hospitals and nursing homes",
        "label": "5 - Institutional: Hospital employees",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 25,
        "wc_female": 25,
        "lav_male": 35,
        "lav_female": 35,
        "bath": None,
        "drinking": 100,
        "other": None,
        "service_sink": None,
        "separate_facilities_rule": "general",
    },
    {
        "key": "institutional_visitors_hospitals",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Visitors in hospitals and nursing homes",
        "label": "5 - Institutional: Hospital visitors",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 75,
        "wc_female": 75,
        "lav_male": 100,
        "lav_female": 100,
        "bath": None,
        "drinking": 500,
        "other": None,
        "service_sink": None,
        "separate_facilities_rule": "general",
    },
    {
        "key": "institutional_reformatories",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Reformatories, detention centers and correctional centers",
        "label": "5 - Institutional: Reformatories, detention",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 15,
        "wc_female": 15,
        "lav_male": 15,
        "lav_female": 15,
        "bath": 15,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    {
        "key": "institutional_employees_reformatories",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Employees in reformatories, detention centers and correctional centers",
        "label": "5 - Institutional: Reformatory employees",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 25,
        "wc_female": 25,
        "lav_male": 35,
        "lav_female": 35,
        "bath": None,
        "drinking": 100,
        "other": None,
        "service_sink": None,
        "separate_facilities_rule": "general",
    },
    {
        "key": "institutional_day_care",
        "classification_no": 5,
        "classification": "Institutional",
        "description": "Adult day care and child day care",
        "label": "5 - Institutional: Day care",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 15,
        "wc_female": 15,
        "lav_male": 15,
        "lav_female": 15,
        "bath": {"fixed": 1},
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
    # --- 6  Mercantile ---
    {
        "key": "mercantile",
        "classification_no": 6,
        "classification": "Mercantile",
        "description": "Retail stores, service stations, shops, salesrooms, markets and shopping centers",
        "label": "6 - Mercantile",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 500,
        "wc_female": 500,
        "lav_male": 750,
        "lav_female": 750,
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "mercantile",
    },
    # --- 7  Residential (calculable only) ---
    {
        "key": "residential_dormitories",
        "classification_no": 7,
        "classification": "Residential",
        "description": "Dormitories, fraternities, sororities and boarding houses (not transient)",
        "label": "7 - Residential: Dormitories",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 10,
        "wc_female": 10,
        "lav_male": 10,
        "lav_female": 10,
        "bath": 8,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "residential",
    },
    {
        "key": "residential_congregate_living",
        "classification_no": 7,
        "classification": "Residential",
        "description": "Congregate living facilities with 16 or fewer persons",
        "label": "7 - Residential: Congregate living",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 10,
        "wc_female": 10,
        "lav_male": 10,
        "lav_female": 10,
        "bath": 8,
        "drinking": 100,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "residential",
    },
    # --- 8  Storage ---
    {
        "key": "storage",
        "classification_no": 8,
        "classification": "Storage",
        "description": "Structures for the storage of goods, warehouses, storehouses and freight depots, low and moderate hazard",
        "label": "8 - Storage",
        "code_ref": "IBC 2021 Table B2902.1",
        "wc_male": 100,
        "wc_female": 100,
        "lav_male": 100,
        "lav_female": 100,
        "bath": None,
        "drinking": 1000,
        "other": "1 service sink",
        "service_sink": {"fixed": 1},
        "separate_facilities_rule": "general",
    },
]

SEPARATE_FACILITIES_RULES = {
    "general": {
        "required": True,
        "exceptions": [],
    },
    "business": {
        "required": True,
        "exceptions": [
            {"max_occupants": 25, "text": "Exception 4: Separate facilities not required in business occupancies where maximum occupant load is 25 or fewer (IBC B2902.2)"},
        ],
    },
    "mercantile": {
        "required": True,
        "exceptions": [
            {"max_occupants": 100, "text": "Exception 3: Separate facilities not required in mercantile occupancies where maximum occupant load is 100 or fewer (IBC B2902.2)"},
        ],
    },
    "residential": {
        "required": False,
        "exceptions": [
            {"text": "Exception 1: Separate facilities not required for dwelling units and sleeping units (IBC B2902.2)"},
        ],
    },
}

LEGACY_PLUMBING_KEY_MAP = {
    "a1_assembly_theaters": "assembly_theaters",
    "a2_assembly_food_drink": "assembly_restaurants",
    "a3_assembly_general": "assembly_auditoriums",
    "business": "business",
    "educational": "educational",
    "factory_industrial": "factory_industrial",
    "mercantile": "mercantile",
    "residential": "residential_dormitories",
    "storage": "storage",
}

PLUMBING_CATEGORY_DEFAULTS = {
    "accessory_storage_gross": "storage",
    "agricultural_gross": "factory_industrial",
    "aircraft_hangar_gross": "factory_industrial",
    "airport_terminal_baggage_gross": "assembly_passenger_terminals",
    "airport_terminal_ticketing_gross": "assembly_passenger_terminals",
    "assembly_concentrated_net": "assembly_auditoriums",
    "assembly_standing_net": "assembly_auditoriums",
    "assembly_unconcentrated_net": "assembly_restaurants",
    "assembly_exhibit_gallery_net": "assembly_auditoriums",
    "assembly_gaming_floor_net": "assembly_casino_gaming",
    "assembly_skating_rink_net": "assembly_coliseums_indoor",
    "assembly_stage_net": "assembly_theaters",
    "assembly_waiting_areas_gross": "assembly_auditoriums",
    "business_gross": "business",
    "courtroom_other_gross": "business",
    "courtroom_seating_fixed": "assembly_auditoriums",
    "day_care_gross": "institutional_day_care",
    "dormitory_gross": "residential_dormitories",
    "educational_classroom_net": "educational",
    "exercise_gross": "assembly_auditoriums",
    "factory_industrial_gross": "factory_industrial",
    "industrial_gross": "factory_industrial",
    "institutional_inpatient_treatment_gross": "institutional_employees_hospitals",
    "institutional_outpatient_gross": "institutional_visitors_hospitals",
    "kitchen_commercial_gross": "business",
    "library_reading_rooms_net": "business",
    "library_stack_gross": "business",
    "locker_room_gross": "assembly_auditoriums",
    "mall_building_covered_gross": "mercantile",
    "mercantile_sales_gross": "mercantile",
    "mercantile_stockroom_gross": "storage",
    "residential_gross": "residential_congregate_living",
    "residential_boarding_gross": "residential_congregate_living",
    "skateboard_tennis_gross": "assembly_stadiums_outdoor",
    "storage_warehouse_gross": "storage",
    "waiting_areas_gross": "assembly_passenger_terminals",
}
